services:
  postgres-db:
    image: postgres:16
    container_name: num-postgres-db
    environment:
      - POSTGRES_USER=num_user
      - POSTGRES_PASSWORD=num_password
      - POSTGRES_DB=num_lost_found
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  auth-service:
    build: ./auth-service
    container_name: num-auth-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/num_lost_found
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=num_user
      - SPRING_DATASOURCE_PASSWORD=num_password
    depends_on:
      - postgres-db

  item-service:
    build: ./item-service
    container_name: num-item-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/num_lost_found
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=num_user
      - SPRING_DATASOURCE_PASSWORD=num_password
    depends_on:
      - postgres-db

  matching-service:
    build: ./matching-service
    container_name: num-matching-service
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - ITEM_SERVICE_URL=http://item-service:8082
    depends_on:
      - item-service

  claim-service:
    build: ./claim-service
    container_name: num-claim-service
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/num_lost_found
      - SPRING_DATASOURCE_DRIVER=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=num_user
      - SPRING_DATASOURCE_PASSWORD=num_password
    depends_on:
      - postgres-db
      - item-service
      - matching-service

  file-service:
    build: ./file-service
    container_name: num-file-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - UPLOAD_DIR=/app/uploads
    volumes:
      - file-uploads:/app/uploads

  api-gateway:
    build: ./api-gateway
    container_name: num-api-gateway
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:8081
      - ITEM_SERVICE_URL=http://item-service:8082
      - MATCHING_SERVICE_URL=http://matching-service:8083
      - CLAIM_SERVICE_URL=http://claim-service:8084
      - FILE_SERVICE_URL=http://file-service:8085
    depends_on:
      - auth-service
      - item-service
      - matching-service
      - claim-service
      - file-service

volumes:
  postgres-data:
  file-uploads:
